name: Deploy to Netlify

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        npm cache clean --force
        npm install

    # Step 5: Deploy to Netlify
    - name: Deploy to Netlify
      env:
        NETLIFY_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }} 
        SITE_ID: ${{ secrets.NETLIFY_SITE_ID }} 
      run: |
        # Install the Netlify CLI
        npm install -g netlify-cli
        
        # Deploy the application to Netlify using the CLI
        netlify deploy --prod --auth $NETLIFY_TOKEN --site $SITE_ID
